# Generated by Django 3.0.6 on 2020-06-02 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chef',
            name='favorites',
            field=models.ManyToManyField(default=None, related_name='favorites', to='recipes.Recipe'),
        ),
    ]
